// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALBX9vqWu6hW4l35uzXaQMGg96EYyODqA',
    appId: '1:814733654823:android:3fc742d276dd34f8904702',
    messagingSenderId: '814733654823',
    projectId: 'autoiq-cc81c',
    databaseURL: 'https://autoiq-cc81c-default-rtdb.firebaseio.com',
    storageBucket: 'autoiq-cc81c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz6IRJisFZa50x4SUpoNPe1JfQVJIZJKo',
    appId: '1:814733654823:ios:95cb3145c29afdf9904702',
    messagingSenderId: '814733654823',
    projectId: 'autoiq-cc81c',
    databaseURL: 'https://autoiq-cc81c-default-rtdb.firebaseio.com',
    storageBucket: 'autoiq-cc81c.firebasestorage.app',
    androidClientId: '814733654823-636d28en11e4465f1i36rr4in24fjh0f.apps.googleusercontent.com',
    iosClientId: '814733654823-m5t6591an7g364n2bpnvcf1uufimk3h4.apps.googleusercontent.com',
    iosBundleId: 'com.capgemini.capgemini',
  );
}
